<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sim</string>
	</array>
	<key>name</key>
	<string>Simula DEMOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\!.+?;</string>
			<key>name</key>
			<string>comment.line.character.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.+?\'</string>
			<key>name</key>
			<string>string.quoted.single.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".+?\"</string>
			<key>name</key>
			<string>string.quoted.double.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(after|and|before|begin|class|delay|do|else|end|eq|eqv|external|for|ge|go|goto|gt|hidden|if|imp|in|inner|inspect|is|le|lt|name|ne|new|none|not|notext|or|otherwise|prior|procedure|protected|qua|reactive|ref|step|switch|then|this|to|until|value|virtual|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(array|boolean|character|integer|long|real|short|text)\b</string>
			<key>name</key>
			<string>storage.type.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\.?\b</string>
			<key>name</key>
			<string>constant.numeric.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\@|\$|\?|\-|\+|\*|\/|\!|\~|\%|\^|\&amp;|\||:=|:-|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(outtext|outreal|outint|outfix|outimage|edit)\b</string>
			<key>name</key>
			<string>support.function.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(bdist|bin|constant|count|dist|draw|empirical|entity|erlang|negexp|normal|poisson|queue|randint|rdist|res|tally|uniform|waitq|condq)\b</string>
			<key>name</key>
			<string>support.class.simulademos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(acquire|avail|cancel|coopt|current|demos|extime|find|first|give|histogram|hold|idle|into|last|length|nextev|notrace|now|out|release|repeat|report|reset|sample|schedule|signal|take|time|trace|update|wait|waituntil)\b</string>
			<key>name</key>
			<string>support.function.simulademos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.simulademos</string>
	<key>uuid</key>
	<string>00e33390-a82e-4e24-bdb0-290d21180d29</string>
</dict>
</plist>
